# @format

name: Nightly Dicts Build

on:
  schedule:
    - cron: "0 16 * * *" # UTC 时间每天 16:00 (北京时间 0:00)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Download and Extract wanxiang.zip
        run: |
          curl -L -o wanxiang.zip https://github.com/amzxyz/rime-wanxiang/archive/refs/heads/wanxiang.zip
          unzip -j wanxiang.zip "rime-wanxiang-wanxiang/dicts/*" -d dicts/
          file_list=(
            "dicts/abbrev.dict.yaml"
            "dicts/t9_abbrev.dict.yaml"
            "dicts/custom_phrase.dict.yaml"
          )
          for _file in "${file_list[@]}"; do
            if [[ -e "$_file" ]]; then
              rm -vf "$_file"
            fi
          done

      - name: Download extra dict
        run: |
          # Download moegirl.dict.yaml from the latest release of suiginko/moetype
          curl -L -o dicts/moegirl.dict.yaml https://github.com/suiginko/moetype/releases/latest/download/moe.dict.yaml
          # Download suzi.dict.yaml and yidu.dict.yaml from the wanxiang_yoemin repository
          curl -L -o dicts/suzi.dict.yaml    https://raw.githubusercontent.com/yuanz-12/wanxiang_yoemin/refs/heads/main/dicts/suzi.pro.dict.yaml
          curl -L -o dicts/yidu.dict.yaml    https://raw.githubusercontent.com/yuanz-12/wanxiang_yoemin/refs/heads/main/dicts/yidu.pro.dict.yaml

      - name: Run aux_go.py && zian_go.py
        run: |
          # Remove auxiliary data and copy the computer dict to the dicts directory
          sed -Ei 's/;\S*//g' dicts/suzi.dict.yaml
          sed -Ei 's/;\S*//g' dicts/yidu.dict.yaml
          cp shared/dicts_extra/computer.dict.yaml dicts
          # Run the scripts
          python tools/tone_convert.py    -i dicts/*.dict.yaml           -o dicts-base
          python tools/zian_go.py         -i dicts-base/*.dict.yaml      -o dicts-zian-base
          python tools/tone_reverse.py    -i dicts-base/*.dict.yaml      -o dicts-tone
          python tools/tone_reverse.py    -i dicts-zian-base/*.dict.yaml -o dicts-zian-tone
          python tools/pinyin_to_flypy.py -i dicts-base/*.dict.yaml      -o dicts-flypy
          python tools/pinyin_to_flypy.py -i dicts-zian-base/*.dict.yaml -o dicts-zian-flypy

      - name: Package dicts
        run: |
          # Create tar.bz2 files for each dicts directory
          tar -cjf "dicts-tone.tar.bz2"       -C "dicts-tone" .
          tar -cjf "dicts-zian-tone.tar.bz2"  -C "dicts-zian-tone" .
          tar -cjf "dicts-flypy.tar.bz2"      -C "dicts-flypy" .
          tar -cjf "dicts-zian-flypy.tar.bz2" -C "dicts-zian-flypy" .
          tar -cjf "NekoCatppuccin.tar.bz2"   -C "themes" .

      - name: Create Nightly release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: nightly
          prerelease: true
          title: "Nightly Build"
          files: |
            dicts-tone.tar.bz2
            dicts-zian-tone.tar.bz2
            dicts-flypy.tar.bz2
            dicts-zian-flypy.tar.bz2
            NekoCatppuccin.tar.bz2
